name: "🎉 Feature Request"
description: Sugest a new feature request or improvement on the project
title: '[Feature]: '
labels:
  - feature
  - triage-needed

body:
  - type: markdown
    attributes:
      value: |
        Please, provide as many information, and knowledge so the feature can be correctly designed and developed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: How the project can be improved?
      description: Can you tell us, how we can improve this project event more?
      placeholder: Feature request
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vuestorefront/magento2/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
